### ISSUE TITLE
`innerHtml` can cause runtime errors

### ISSUE THREAD

**Issue by hecrj** [elm-community/html-extra#15]
Using `innerHtml` can conflict with the virtual-dom diffing algorithm, causing a crash, as seen here: https://ellie-app.com/9Kbn9hPFha1/1

This was mentioned some time ago here: https://github.com/elm-lang/html/issues/56#issuecomment-235524657

Maybe `innerHtml` should be removed?

**Comment by rgrempel** [comment]
For anyone needing a temporary workaround, it is possible to mitigate this problem, at least in many cases, by using ‘keyed’ nodes to give the virtual DOM a hint.

**Comment by hecrj** [comment]
Closing this as `innerHtml` is forbidden in Elm 0.19.
